# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 02:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import planner.auth


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('document_type', models.CharField(choices=[('TI', 'Tarjeta de Identidad'), ('CC', 'Cedula de Ciudadania'), ('CE', 'Cedula de Extranjer\xeda')], default='CC', max_length=5)),
                ('document_number', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('birthdate', models.DateField(null=True)),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Other')], max_length=2)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=30)),
                ('role', models.CharField(choices=[('R', 'Root'), ('A', 'Administrador'), ('S', 'Agricultor')], max_length=1)),
                ('is_active', models.BooleanField(default=False)),
                ('join_date', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', planner.auth.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Ano_cipc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Ano_costo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Anos_mo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Base_presupuestal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='bp', max_length=125)),
                ('rentabilidad', models.FloatField(default=0)),
                ('cipc', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bp_cipc', to='planner.Ano_cipc')),
            ],
        ),
        migrations.CreateModel(
            name='CIPC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gastosGenerales', models.FloatField(default=100)),
                ('prestacionesSociales', models.FloatField(default=200)),
                ('impuestoPredial', models.FloatField(default=3000)),
                ('gastosFinancieros', models.FloatField(default=200)),
            ],
        ),
        migrations.CreateModel(
            name='Costos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidadSitio', models.FloatField(default=2)),
                ('cantidadHectarea', models.FloatField(default=4)),
                ('frecuencia', models.FloatField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Costos_insumos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biocontroladores', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='biocontroladores_anocosto', to='planner.Ano_costo')),
                ('bombasEspalda', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bombasEspalda_anocosto', to='planner.Ano_costo')),
                ('bombasEstacionarias', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bombasEstacionarias_anocosto', to='planner.Ano_costo')),
                ('canastillas', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='canastillas_costos', to='planner.Ano_costo')),
                ('fertilizante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fertilizante_anocosto', to='planner.Ano_costo')),
                ('fertilizanteFoliar', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fertilizanteFoliar_anocosto', to='planner.Ano_costo')),
                ('fungicidas', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fungicidas_anocosto', to='planner.Ano_costo')),
                ('herbicidaCalles', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='herbicidaCalles_anocosto', to='planner.Ano_costo')),
                ('herbicidaPlatos', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='herbicidaPlatos_anocosto', to='planner.Ano_costo')),
                ('insecticidas', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='insecticidas_anocosto', to='planner.Ano_costo')),
                ('materiaOrganica', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='materiaOrganica_anocosto', to='planner.Ano_costo')),
                ('ridomil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ridomil_anocosto', to='planner.Ano_costo')),
                ('selectores', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='selectores_anocosto', to='planner.Ano_costo')),
            ],
        ),
        migrations.CreateModel(
            name='Data_mo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rendimiento', models.FloatField(default=30)),
                ('frecuencia', models.FloatField(default=3)),
                ('unidad', models.CharField(default='jor/dia', max_length=125)),
            ],
        ),
        migrations.CreateModel(
            name='Datos_generales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(default='empresa', max_length=125)),
                ('departamento', models.CharField(default='Risaralda', max_length=125)),
                ('vereda', models.CharField(default='El cedral', max_length=125)),
                ('gastos_operacionales', models.FloatField(default=300)),
                ('valor_de_tierra', models.FloatField(default=400)),
                ('densidad', models.FloatField(default=400)),
                ('jornal', models.FloatField(default=3000)),
                ('altitud', models.FloatField(default=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Distribucion_calidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Establecimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preparacionTerreno', models.FloatField(default=200)),
                ('trazo', models.FloatField(default=200)),
                ('hoyado', models.FloatField(default=100)),
                ('distribucionColino', models.FloatField(default=342)),
                ('aplicacionCorrectivos', models.FloatField(default=232)),
                ('aplicacionMicorriza', models.FloatField(default=700)),
                ('aplicacionMateriaOrganica', models.FloatField(default=102)),
                ('siembra', models.FloatField(default=200)),
                ('resiembra', models.FloatField(default=300)),
            ],
        ),
        migrations.CreateModel(
            name='Finca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('area', models.FloatField()),
                ('agricultor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finca_agricultor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Insumos_generales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arbol', models.FloatField()),
                ('fungicida', models.FloatField()),
                ('insecticida', models.FloatField()),
                ('herbicida', models.FloatField()),
                ('canatillas', models.FloatField()),
                ('proteina_hidrolizada', models.FloatField()),
                ('coadyuvantes', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Insumos_mo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aplicacionHerbicida', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aplicacionHerbicida_anosmo', to='planner.Anos_mo')),
                ('aplicacionMateriaOrganica', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aplicacionMateriaOrganica_anosmo', to='planner.Anos_mo')),
                ('aspersiones', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aspersiones_anosmo', to='planner.Anos_mo')),
                ('biocontroladores', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='biocontroladores_anosmo', to='planner.Anos_mo')),
                ('fertilizacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fertilizacion_anosmo', to='planner.Anos_mo')),
                ('fungicidas', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fungicidas_anosmo', to='planner.Anos_mo')),
                ('limpiaGuadanaCalles', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='limpiaGuadanacalles_anosmo', to='planner.Anos_mo')),
                ('plateo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plateo_anosmo', to='planner.Anos_mo')),
                ('podas', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='podas_anosmo', to='planner.Anos_mo')),
                ('recoleccionContrato', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recoleccionContrato_anosmo', to='planner.Anos_mo')),
                ('recoleccionDia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recoleccionDia_anosmo', to='planner.Anos_mo')),
                ('resiembra', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resiembra_anosmo', to='planner.Anos_mo')),
                ('siembra', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='siembra_anosmo', to='planner.Anos_mo')),
                ('tutorado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tutorado_anosmo', to='planner.Anos_mo')),
            ],
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='lote', max_length=150)),
                ('tipo', models.CharField(max_length=150)),
                ('cultivo', models.CharField(max_length=150)),
                ('variedad', models.CharField(max_length=150)),
                ('edad', models.FloatField()),
                ('area', models.FloatField()),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lote_finca', to='planner.Finca')),
            ],
        ),
        migrations.CreateModel(
            name='lote_has_bp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotebp_bp', to='planner.Base_presupuestal')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotebp_lote', to='planner.Lote')),
            ],
        ),
        migrations.CreateModel(
            name='Porcentaje_precio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.FloatField()),
                ('porcentaje', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Preparacion_costos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cal_costos', to='planner.Costos')),
                ('colino', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='colino_costos', to='planner.Costos')),
                ('dap', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dap_costos', to='planner.Costos')),
                ('estacas', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estacas_costos', to='planner.Costos')),
                ('herbicida', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='herbicida_costos', to='planner.Costos')),
                ('herramientas', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='herramientas_costos', to='planner.Costos')),
                ('lycra', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lycra_costos', to='planner.Costos')),
                ('materiaOrganica', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='materiaOrganicapulpa_costos', to='planner.Costos')),
                ('melaza', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='melaza_costos', to='planner.Costos')),
                ('micorriza', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='micorriza_costos', to='planner.Costos')),
                ('paecilomyces', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paecilomyces_costos', to='planner.Costos')),
                ('trichoderma', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trichoderma_costos', to='planner.Costos')),
                ('vinilo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vinilo_costos', to='planner.Costos')),
            ],
        ),
        migrations.CreateModel(
            name='Produccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano1', models.FloatField(default=120)),
                ('ano2', models.FloatField(default=120)),
                ('ano3', models.FloatField(default=120)),
                ('ano4', models.FloatField(default=120)),
                ('ano5', models.FloatField(default=120)),
                ('ano6', models.FloatField(default=120)),
                ('ano7', models.FloatField(default=120)),
                ('ano8', models.FloatField(default=120)),
                ('ano9', models.FloatField(default=120)),
                ('ano10', models.FloatField(default=120)),
                ('ano11', models.FloatField(default=120)),
                ('ano12', models.FloatField(default=120)),
                ('ano13', models.FloatField(default=120)),
                ('ano14', models.FloatField(default=120)),
                ('ano15', models.FloatField(default=120)),
            ],
        ),
        migrations.CreateModel(
            name='Riesgo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mercado', models.FloatField()),
                ('fitosanitario', models.FloatField()),
                ('fluctuacion_precio', models.FloatField()),
                ('administracion', models.FloatField()),
                ('tecnologia', models.FloatField()),
                ('mano_de_obra', models.FloatField()),
                ('clima', models.FloatField()),
                ('perecedero', models.FloatField()),
                ('agremiacion', models.FloatField()),
                ('inseguridad', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='lote',
            name='riesgo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lote_riesgo', to='planner.Riesgo'),
        ),
        migrations.AddField(
            model_name='distribucion_calidad',
            name='primera',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dc_primera', to='planner.Porcentaje_precio'),
        ),
        migrations.AddField(
            model_name='distribucion_calidad',
            name='produccion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dc_produccion', to='planner.Produccion'),
        ),
        migrations.AddField(
            model_name='distribucion_calidad',
            name='segunda',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dc_segunda', to='planner.Porcentaje_precio'),
        ),
        migrations.AddField(
            model_name='distribucion_calidad',
            name='tercera',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dc_tercera', to='planner.Porcentaje_precio'),
        ),
        migrations.AddField(
            model_name='base_presupuestal',
            name='costos_insumos',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bp_Costosinsumos', to='planner.Costos_insumos'),
        ),
        migrations.AddField(
            model_name='base_presupuestal',
            name='datos_g',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bp_dg', to='planner.Datos_generales'),
        ),
        migrations.AddField(
            model_name='base_presupuestal',
            name='distribucion_calidad',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bp_dc', to='planner.Distribucion_calidad'),
        ),
        migrations.AddField(
            model_name='base_presupuestal',
            name='insumos_g',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bp_ig', to='planner.Insumos_generales'),
        ),
        migrations.AddField(
            model_name='base_presupuestal',
            name='insumos_mo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bp_insumosmo', to='planner.Insumos_mo'),
        ),
        migrations.AddField(
            model_name='base_presupuestal',
            name='preparacion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bp_preparacion', to='planner.Preparacion_costos'),
        ),
        migrations.AddField(
            model_name='anos_mo',
            name='ano1',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ano1_datamo', to='planner.Data_mo'),
        ),
        migrations.AddField(
            model_name='anos_mo',
            name='ano10',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ano10_datamo', to='planner.Data_mo'),
        ),
        migrations.AddField(
            model_name='anos_mo',
            name='ano11',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ano11_datamo', to='planner.Data_mo'),
        ),
        migrations.AddField(
            model_name='anos_mo',
            name='ano12',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ano12_datamo', to='planner.Data_mo'),
        ),
        migrations.AddField(
            model_name='anos_mo',
            name='ano13',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ano13_datamo', to='planner.Data_mo'),
        ),
        migrations.AddField(
            model_name='anos_mo',
            name='ano14',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ano14_datamo', to='planner.Data_mo'),
        ),
        migrations.AddField(
            model_name='anos_mo',
            name='ano15',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ano15_datamo', to='planner.Data_mo'),
        ),
        migrations.AddField(
            model_name='anos_mo',
            name='ano2',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ano2_datamo', to='planner.Data_mo'),
        ),
        migrations.AddField(
            model_name='anos_mo',
            name='ano3',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ano3_datamo', to='planner.Data_mo'),
        ),
        migrations.AddField(
            model_name='anos_mo',
            name='ano4',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ano4_datamo', to='planner.Data_mo'),
        ),
        migrations.AddField(
            model_name='anos_mo',
            name='ano5',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ano5_datamo', to='planner.Data_mo'),
        ),
        migrations.AddField(
            model_name='anos_mo',
            name='ano6',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ano6_datamo', to='planner.Data_mo'),
        ),
        migrations.AddField(
            model_name='anos_mo',
            name='ano7',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ano7_datamo', to='planner.Data_mo'),
        ),
        migrations.AddField(
            model_name='anos_mo',
            name='ano8',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ano8_datamo', to='planner.Data_mo'),
        ),
        migrations.AddField(
            model_name='anos_mo',
            name='ano9',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ano9_datamo', to='planner.Data_mo'),
        ),
        migrations.AddField(
            model_name='ano_costo',
            name='ano1',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ano1_datamo', to='planner.Costos'),
        ),
        migrations.AddField(
            model_name='ano_costo',
            name='ano10',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ano10_datamo', to='planner.Costos'),
        ),
        migrations.AddField(
            model_name='ano_costo',
            name='ano11',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ano11_datamo', to='planner.Costos'),
        ),
        migrations.AddField(
            model_name='ano_costo',
            name='ano12',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ano12_datamo', to='planner.Costos'),
        ),
        migrations.AddField(
            model_name='ano_costo',
            name='ano13',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ano13_datamo', to='planner.Costos'),
        ),
        migrations.AddField(
            model_name='ano_costo',
            name='ano14',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ano14_datamo', to='planner.Costos'),
        ),
        migrations.AddField(
            model_name='ano_costo',
            name='ano15',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ano15_datamo', to='planner.Costos'),
        ),
        migrations.AddField(
            model_name='ano_costo',
            name='ano2',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ano2_datamo', to='planner.Costos'),
        ),
        migrations.AddField(
            model_name='ano_costo',
            name='ano3',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ano3_datamo', to='planner.Costos'),
        ),
        migrations.AddField(
            model_name='ano_costo',
            name='ano4',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ano4_datamo', to='planner.Costos'),
        ),
        migrations.AddField(
            model_name='ano_costo',
            name='ano5',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ano5_datamo', to='planner.Costos'),
        ),
        migrations.AddField(
            model_name='ano_costo',
            name='ano6',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ano6_datamo', to='planner.Costos'),
        ),
        migrations.AddField(
            model_name='ano_costo',
            name='ano7',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ano7_datamo', to='planner.Costos'),
        ),
        migrations.AddField(
            model_name='ano_costo',
            name='ano8',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ano8_datamo', to='planner.Costos'),
        ),
        migrations.AddField(
            model_name='ano_costo',
            name='ano9',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ano9_datamo', to='planner.Costos'),
        ),
        migrations.AddField(
            model_name='ano_cipc',
            name='ano1',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ano1_datamo', to='planner.CIPC'),
        ),
        migrations.AddField(
            model_name='ano_cipc',
            name='ano10',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ano10_datamo', to='planner.CIPC'),
        ),
        migrations.AddField(
            model_name='ano_cipc',
            name='ano11',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ano11_datamo', to='planner.CIPC'),
        ),
        migrations.AddField(
            model_name='ano_cipc',
            name='ano12',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ano12_datamo', to='planner.CIPC'),
        ),
        migrations.AddField(
            model_name='ano_cipc',
            name='ano13',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ano13_datamo', to='planner.CIPC'),
        ),
        migrations.AddField(
            model_name='ano_cipc',
            name='ano14',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ano14_datamo', to='planner.CIPC'),
        ),
        migrations.AddField(
            model_name='ano_cipc',
            name='ano15',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ano15_datamo', to='planner.CIPC'),
        ),
        migrations.AddField(
            model_name='ano_cipc',
            name='ano2',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ano2_datamo', to='planner.CIPC'),
        ),
        migrations.AddField(
            model_name='ano_cipc',
            name='ano3',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ano3_datamo', to='planner.CIPC'),
        ),
        migrations.AddField(
            model_name='ano_cipc',
            name='ano4',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ano4_datamo', to='planner.CIPC'),
        ),
        migrations.AddField(
            model_name='ano_cipc',
            name='ano5',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ano5_datamo', to='planner.CIPC'),
        ),
        migrations.AddField(
            model_name='ano_cipc',
            name='ano6',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ano6_datamo', to='planner.CIPC'),
        ),
        migrations.AddField(
            model_name='ano_cipc',
            name='ano7',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ano7_datamo', to='planner.CIPC'),
        ),
        migrations.AddField(
            model_name='ano_cipc',
            name='ano8',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ano8_datamo', to='planner.CIPC'),
        ),
        migrations.AddField(
            model_name='ano_cipc',
            name='ano9',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ano9_datamo', to='planner.CIPC'),
        ),
    ]
