# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 05:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finca',
            name='area',
            field=models.FloatField(default=32000),
        ),
        migrations.AlterField(
            model_name='finca',
            name='name',
            field=models.CharField(default='FincaVerde', max_length=150),
        ),
        migrations.AlterField(
            model_name='insumos_generales',
            name='arbol',
            field=models.FloatField(default=400),
        ),
        migrations.AlterField(
            model_name='insumos_generales',
            name='canatillas',
            field=models.FloatField(default=400),
        ),
        migrations.AlterField(
            model_name='insumos_generales',
            name='coadyuvantes',
            field=models.FloatField(default=400),
        ),
        migrations.AlterField(
            model_name='insumos_generales',
            name='fungicida',
            field=models.FloatField(default=400),
        ),
        migrations.AlterField(
            model_name='insumos_generales',
            name='herbicida',
            field=models.FloatField(default=400),
        ),
        migrations.AlterField(
            model_name='insumos_generales',
            name='insecticida',
            field=models.FloatField(default=400),
        ),
        migrations.AlterField(
            model_name='insumos_generales',
            name='proteina_hidrolizada',
            field=models.FloatField(default=400),
        ),
        migrations.AlterField(
            model_name='lote',
            name='area',
            field=models.FloatField(default=4000),
        ),
        migrations.AlterField(
            model_name='lote',
            name='cultivo',
            field=models.CharField(default='Verde', max_length=150),
        ),
        migrations.AlterField(
            model_name='lote',
            name='edad',
            field=models.FloatField(default=3),
        ),
        migrations.AlterField(
            model_name='lote',
            name='name',
            field=models.CharField(default='Lote', max_length=150),
        ),
        migrations.AlterField(
            model_name='lote',
            name='tipo',
            field=models.CharField(default='Verde', max_length=150),
        ),
        migrations.AlterField(
            model_name='lote',
            name='variedad',
            field=models.CharField(default='Verde', max_length=150),
        ),
        migrations.AlterField(
            model_name='riesgo',
            name='administracion',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='riesgo',
            name='agremiacion',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='riesgo',
            name='clima',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='riesgo',
            name='fitosanitario',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='riesgo',
            name='fluctuacion_precio',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='riesgo',
            name='inseguridad',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='riesgo',
            name='mano_de_obra',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='riesgo',
            name='mercado',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='riesgo',
            name='perecedero',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='riesgo',
            name='tecnologia',
            field=models.FloatField(default=1),
        ),
    ]
