# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 18:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_auto_20170722_0507'),
    ]

    operations = [
        migrations.AddField(
            model_name='base_presupuestal',
            name='establecimiento',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bp_establecimiento', to='planner.Establecimiento'),
        ),
    ]
