# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 03:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_auto_20170722_1902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preparacion_costos',
            name='herbicida',
        ),
        migrations.RemoveField(
            model_name='preparacion_costos',
            name='herramientas',
        ),
        migrations.RemoveField(
            model_name='preparacion_costos',
            name='lycra',
        ),
        migrations.RemoveField(
            model_name='preparacion_costos',
            name='materiaOrganica',
        ),
        migrations.AddField(
            model_name='costos_insumos',
            name='guadana',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='guadana_anocosto', to='planner.Ano_costo'),
        ),
        migrations.AddField(
            model_name='costos_insumos',
            name='herramientas',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='herramientas_anocosto', to='planner.Ano_costo'),
        ),
        migrations.AddField(
            model_name='costos_insumos',
            name='lycra',
            field=models.OneToOneField(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='lycra_anocosto', to='planner.Ano_costo'),
        ),
        migrations.AddField(
            model_name='preparacion_costos',
            name='resiembra',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='resiembra_costos', to='planner.Costos'),
        ),
        migrations.AlterField(
            model_name='costos_insumos',
            name='canastillas',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='canastillas_anocosto', to='planner.Ano_costo'),
        ),
    ]
