# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 03:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0005_auto_20170723_0352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costos_insumos',
            name='guadana',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guadana_anocosto', to='planner.Ano_costo'),
        ),
        migrations.AlterField(
            model_name='costos_insumos',
            name='herramientas',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='herramientas_anocosto', to='planner.Ano_costo'),
        ),
        migrations.AlterField(
            model_name='costos_insumos',
            name='lycra',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lycra_anocosto', to='planner.Ano_costo'),
        ),
        migrations.AlterField(
            model_name='preparacion_costos',
            name='resiembra',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resiembra_costos', to='planner.Costos'),
        ),
    ]
