# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 05:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0006_auto_20170723_0353'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumos_generales',
            name='fertilizante',
            field=models.FloatField(default=400),
        ),
        migrations.AddField(
            model_name='insumos_generales',
            name='materiaOrganica',
            field=models.FloatField(default=400),
        ),
        migrations.AddField(
            model_name='insumos_generales',
            name='ridomil',
            field=models.FloatField(default=400),
        ),
    ]
