# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 01:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0008_auto_20170726_0304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finca',
            name='area',
            field=models.FloatField(default=320),
        ),
        migrations.AlterField(
            model_name='finca',
            name='name',
            field=models.CharField(default='Finca', max_length=150),
        ),
        migrations.AlterField(
            model_name='lote',
            name='area',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='lote',
            name='cultivo',
            field=models.CharField(choices=[('agroforestal', 'Agroforestal'), ('lulo', 'Lulo'), ('frijol', 'Frijol'), ('mora', 'Mora'), ('zoca', 'Zoca')], max_length=15),
        ),
        migrations.AlterField(
            model_name='lote',
            name='edad',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='lote',
            name='tipo',
            field=models.CharField(choices=[('frutales', 'Frutales'), ('cafe', 'Caf\xe9'), ('forestales', 'Forestales'), ('hortalizas', 'Hortalizas')], max_length=15),
        ),
        migrations.AlterField(
            model_name='lote',
            name='variedad',
            field=models.CharField(choices=[('selva', 'La selva'), ('sin espinas', 'Sin espinas'), ('arbustivo', 'Arbustivo'), ('nogal', 'Nogal'), ('calavera', 'Calavera'), ('bandola', 'Bandola')], max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(auto_now_add=True, verbose_name='last_login'),
        ),
    ]
