# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 02:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0009_auto_20170803_0126'),
    ]

    operations = [
        migrations.AddField(
            model_name='base_presupuestal',
            name='cultivo',
            field=models.CharField(choices=[('agroforestal', 'Agroforestal'), ('lulo', 'Lulo'), ('frijol', 'Frijol'), ('mora', 'Mora'), ('zoca', 'Zoca')], default='frutales', max_length=15),
        ),
        migrations.AddField(
            model_name='base_presupuestal',
            name='tipo',
            field=models.CharField(choices=[('frutales', 'Frutales'), ('cafe', 'Caf\xe9'), ('forestales', 'Forestales'), ('hortalizas', 'Hortalizas')], default='frutales', max_length=15),
        ),
        migrations.AddField(
            model_name='base_presupuestal',
            name='variedad',
            field=models.CharField(choices=[('selva', 'La selva'), ('sin espinas', 'Sin espinas'), ('arbustivo', 'Arbustivo'), ('nogal', 'Nogal'), ('calavera', 'Calavera'), ('bandola', 'Bandola')], default='frutales', max_length=15),
        ),
    ]
