# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 04:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0010_auto_20170803_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base_presupuestal',
            name='cultivo',
            field=models.CharField(choices=[('limon', 'Lim\xf3n'), ('agroforestal', 'Agroforestal'), ('lulo', 'Lulo'), ('frijol', 'Frijol'), ('mora', 'Mora'), ('zoca', 'Zoca')], default='frutales', max_length=15),
        ),
        migrations.AlterField(
            model_name='base_presupuestal',
            name='variedad',
            field=models.CharField(choices=[('tahiti', 'Tahit\xed'), ('selva', 'La selva'), ('sin espinas', 'Sin espinas'), ('arbustivo', 'Arbustivo'), ('nogal', 'Nogal'), ('calavera', 'Calavera'), ('bandola', 'Bandola')], default='frutales', max_length=15),
        ),
        migrations.AlterField(
            model_name='lote',
            name='cultivo',
            field=models.CharField(choices=[('limon', 'Lim\xf3n'), ('agroforestal', 'Agroforestal'), ('lulo', 'Lulo'), ('frijol', 'Frijol'), ('mora', 'Mora'), ('zoca', 'Zoca')], max_length=15),
        ),
        migrations.AlterField(
            model_name='lote',
            name='variedad',
            field=models.CharField(choices=[('tahiti', 'Tahit\xed'), ('selva', 'La selva'), ('sin espinas', 'Sin espinas'), ('arbustivo', 'Arbustivo'), ('nogal', 'Nogal'), ('calavera', 'Calavera'), ('bandola', 'Bandola')], max_length=15),
        ),
        migrations.AlterField(
            model_name='preparacion_costos',
            name='cal',
            field=models.FloatField(default=2),
        ),
        migrations.AlterField(
            model_name='preparacion_costos',
            name='colino',
            field=models.FloatField(default=2),
        ),
        migrations.AlterField(
            model_name='preparacion_costos',
            name='dap',
            field=models.FloatField(default=2),
        ),
        migrations.AlterField(
            model_name='preparacion_costos',
            name='estacas',
            field=models.FloatField(default=2),
        ),
        migrations.AlterField(
            model_name='preparacion_costos',
            name='melaza',
            field=models.FloatField(default=2),
        ),
        migrations.AlterField(
            model_name='preparacion_costos',
            name='micorriza',
            field=models.FloatField(default=2),
        ),
        migrations.AlterField(
            model_name='preparacion_costos',
            name='paecilomyces',
            field=models.FloatField(default=2),
        ),
        migrations.AlterField(
            model_name='preparacion_costos',
            name='resiembra',
            field=models.FloatField(default=2),
        ),
        migrations.AlterField(
            model_name='preparacion_costos',
            name='trichoderma',
            field=models.FloatField(default=2),
        ),
        migrations.AlterField(
            model_name='preparacion_costos',
            name='vinilo',
            field=models.FloatField(default=2),
        ),
    ]
