# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0011_auto_20170804_0442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cipc',
            name='impuestoPredial',
            field=models.FloatField(default=100),
        ),
    ]
