# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-21 00:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0013_auto_20170818_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cultivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cultivo', models.CharField(default='Lim\xf3n', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(default='Frutales', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Variedad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variedad', models.CharField(default='Tahit\xed', max_length=15)),
                ('cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variedad_cultivo', to='planner.Cultivo')),
            ],
        ),
        migrations.RemoveField(
            model_name='base_presupuestal',
            name='cultivo',
        ),
        migrations.RemoveField(
            model_name='base_presupuestal',
            name='variedad',
        ),
        migrations.AlterField(
            model_name='base_presupuestal',
            name='tipo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bp_tipo', to='planner.Tipo'),
        ),
        migrations.AddField(
            model_name='cultivo',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cultivo_variedad', to='planner.Tipo'),
        ),
    ]
