# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-21 00:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0014_auto_20170821_0035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cultivo',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='variedad',
            name='cultivo',
        ),
        migrations.AddField(
            model_name='base_presupuestal',
            name='cultivo',
            field=models.CharField(choices=[('limon', 'Lim\xf3n'), ('agroforestal', 'Agroforestal'), ('lulo', 'Lulo'), ('frijol', 'Frijol'), ('mora', 'Mora'), ('zoca', 'Zoca')], default='Lim\xf3n', max_length=15),
        ),
        migrations.AddField(
            model_name='base_presupuestal',
            name='variedad',
            field=models.CharField(choices=[('tahiti', 'Tahit\xed'), ('selva', 'La selva'), ('sin espinas', 'Sin espinas'), ('arbustivo', 'Arbustivo'), ('nogal', 'Nogal'), ('calavera', 'Calavera'), ('bandola', 'Bandola')], default='Tahit\xed', max_length=15),
        ),
        migrations.AlterField(
            model_name='base_presupuestal',
            name='tipo',
            field=models.CharField(choices=[('frutales', 'Frutales'), ('cafe', 'Caf\xe9'), ('forestales', 'Forestales'), ('hortalizas', 'Hortalizas')], default='Frutales', max_length=15),
        ),
        migrations.DeleteModel(
            name='Cultivo',
        ),
        migrations.DeleteModel(
            name='Tipo',
        ),
        migrations.DeleteModel(
            name='Variedad',
        ),
    ]
